h2 database dependency 추가
DKU54PLAY/student-council-homepage-backend pull request #5
Opened 2022-06-15 11:58 UTC by developerChans

- h2 database

@tco0427  @headF1rst

2022-06-15 17:15 UTC, tco0427 requested changes
리뷰 확인해주세요~_~

2022-06-15 17:15 UTC, tco0427 commented on build.gradle
> +	implementation 'com.h2database:h2'
DB에 대한 의존성 부분과 다른 부분들을 분리해보면 어떨까요?

예를 들어 Spring에 대한 의존성 부분을 `// spring`, 로그 관련된 부분을 `// log`, DB 관련된 부분을 `// DB`

2022-06-16 00:56 UTC, developerChans commented on build.gradle
> +	implementation 'com.h2database:h2'
코드 refact 했습니다.

2022-06-16 01:53 UTC, tco0427 requested changes
한 번만 더 리뷰 확인 부탁드려요~

2022-06-16 01:53 UTC, tco0427 commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
같은 `org.springframework.boot` 으로 묶이니 Spring에 대한 의존성이라고 봐도 될 것 같습니다!

2022-06-16 01:53 UTC, tco0427 commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-web'
같은 `org.springframework.boot` 으로 묶이니 Spring에 대한 의존성이라고 봐도 될 것 같습니다!

2022-06-16 08:13 UTC, merged