BaseResponse 제안(#6)
DKU54PLAY/student-council-homepage-backend pull request #7
Opened 2022-06-15 12:28 UTC by developerChans

CRUD 들어가기 앞서서 제가 주로 postman을 사용해서 
BaseResponse 제안드립니다.

같이 회의해서 진행하지 않은 점 죄송합니다.
연락이 안되어서 정말 의견만 들어보려고 pr 올립니다. 코드 보시고 의견 issue에 남겨주세요
[BaseResponse 작업](https://github.com/DKU54PLAY/student-council-homepage-backend/issues/6)

@headF1rst @tco0427

2022-06-15 17:20 UTC, tco0427 requested changes
안녕하세요 찬진님😁

코드 내용 확인하고 간단하게 코멘트 남겨보았습니다.
확인 부탁드립니다~

2022-06-15 17:20 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +}
코드 맨 마지막에 공백이 없네요. 이렇게 되었을 때 발생하는 문제가 무엇이 있을까요?

2022-06-15 17:20 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +public class BaseException extends Exception {
Exception을 상속하는 이유를 알 수 있을까요??

2022-06-15 17:20 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +@Setter
`BaseResponseStatus` 타입 인스턴스 변수인 status에 대한 setter를 열어둔 이유가 무엇일까요?
그리고 이렇게 열었을 때 발생할 수 있는 문제점은 무엇이 있을까요?

2022-06-15 17:20 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponseStatus.java
> +public enum BaseResponseStatus {
`customer Error` 코드의 장단점을 정리해보면 좋을 것 같습니다!
찬진님이 생각하는 Customer Error Code의 장단점에는 무엇이 있을까요?

2022-06-15 17:20 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponse.java
> +public class BaseResponse<T> {
`org.springframework.http` 패키지에 포함되어 있는 `ResponseEntity`와는 어떤 차이가 있을까요?
`ResponseEntity` 를 활용해서도 충분히 요청 혹은 응답 메시지나 상태 코드 그리고 성공여부를 전달할 수 있지 않을까요?
이렇게 custom class를 썼을 때 얻을 수 있는 이점이 무엇이라고 생각했는지 궁금합니다.🤔

2022-06-16 00:41 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +public class BaseException extends Exception {
오류 또는 예외들을 Exception으로 처리할 예정입니다.
예외들도 Exception으로 처리하는 이유는 작업할 때 어디 부분에서의 예외인지 알기 쉽게 됩니다. 예시를 들면 로직자체의 문제인지, 아니면 database상의 문제인지 예외 처리문을 통해서 어디를 고쳐야할지 더 빨리 알 수 있습니다.

2022-06-16 00:47 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponseStatus.java
> +public enum BaseResponseStatus {
1000번대, 2000번대, 3000번대 등등 Customer Error Code를 사용하게 될 경우 에러나 오류 대한 세분화가 가능해 진다고 생각이 듭니다. 그렇게 될 경우 클라이언트에서도 조금 더 작업하기 편한 환경이 될 것이라 생각했습니다.

2022-06-16 00:48 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +}
파일이 계속 읽힐 수 있겠네요. EOF 처리는 자동으로 되는 줄 알았는데 몰랏습니다.

2022-06-16 00:51 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponseStatus.java
> +public enum BaseResponseStatus {
아무래도 단점으론 모든 메세지를 exception으로 throw해버리면 오류인지 에러인지 잘 구분할 수 없어질 수 있으며, 작업상에서 조금 불편한 점도 있을 것 같네요 위에 custom class 를 썻을때 이점과 같이 커멘트 하겟습니다.

2022-06-16 00:51 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +@Setter
이 부분은 이전에도 setter로 열었어서 잘 모르겠습니다. 혹시 어떤 문제점이 발생할 수 있을까요?

2022-06-16 01:55 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +public class BaseException extends Exception {
Exception은 `Checked Exception`과 `Unchecked Exception` 으로 나뉘게 되는데, 단순히 Exception을 상속하면 이 둘로 구분해주는 건 어떻게 생각하시는지 궁금합니다.
또한 Exception은 너무 큰 범위라는 생각이 드네요..

2022-06-16 01:56 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +@Setter
이건 산하님 포함해서 전체가 알아야 하는 부분이라는 생각이 들어 슬렉 드렸습니다. 슬렉 확인해주세요~_~

2022-06-16 02:07 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponseStatus.java
> +public enum BaseResponseStatus {
맞습니다..!! 오류에 대한 세분화가 가능해질 수 있습니다.
하지만 다음과 같은 고민을 해볼 수 있을 것 같습니다.

가장 먼저 여기서 더 프로젝트의 규모가 커진다면 커스텀 에러를 관리하기 위한 문서를 과연 우리가 계속해서 유지보수 할 수 있겠는가? 라는 질문에 자신있게 "네!" 라고 말하지 못할 것 같다는 생각이 듭니다. 그리고 세분화 되어있다는 부분도 어떤 API 를 호출해서 어떤 상태코드를 받았는가 그리고 errorMessage를 통해서 충분히 알 수 있다고 생각됩니다.

2022-06-16 02:10 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseException.java
> +}
파일 끝부분에 개행을 하지 않으면 git에서 merge하는 과정에 파일의 끝부분이 꼬여서 이상하게 동작할 수 있습니다.
[참고 글](https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/)을 확인해주세요~

2022-06-16 05:18 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponseStatus.java
> +public enum BaseResponseStatus {
흠... 단지, BaseResponseStatus에 관련 번호랑 에러메세지 한 줄 적는 것인데 어렵다고는 생각이 들지 않습니다. 유지보수를 위해서라면, 더더욱 이러한 에러메세지 관리가 필요하다고 생각하는 바입니다.
공통적인 에러 메세지들을 정리하고, api별 에러메세지를 통해서 validation을 진행한다면, 더 좋은 유지보수 환경이 될 수 있지 않을까요? 클라이언트 측에서도 api 명세를 통해 어떠한 경우에 어떤 alert를 띄워야할지 등등 더 쉽게 진행 할 수 있을 것이라 판단하였습니다.

2022-06-17 04:31 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/data/BaseResponseStatus.java
> +public enum BaseResponseStatus {
우선 개발을 시작해야하기 때문에 이 부분은 다음 회의 시간 잡아서 진행하도록하겠습니다. 우선 ResponseEnitiy로 사용법찾아서 사용하겠습니다.

2022-06-17 04:31 UTC, closed without merging