feat : 회원 CRUD issus#2
DKU54PLAY/student-council-homepage-backend pull request #9
Opened 2022-06-19 14:49 UTC by developerChans

회원 CRUD 늦게라도 PR 올립니다. 호되게 혼내주세요

2022-06-19 15:18 UTC, tco0427 requested changes
찬진님! 리뷰 남겼습니다..!
테스트 코드에 대한 누락이 있는 것 같아요ㅠ 확인 후 반영해주시면 감사하겠습니다.

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/domain/User.java
> +    }
컨벤션을 확인해주세요!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/domain/User.java
> +    }
`@AllArgsConstructor`와 어떤 차이가 있을까요??

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/dto/request/SignUpRequest.java
> +    public User toUserEnity() {
오타 발견!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/dto/request/DeleteUserRequest.java
> +    }
다른 곳과 달리 여기서는 `@AllArgsConstructor`를 사용하지 않은 특별한 이유가 있을까요??🤔

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/dto/response/DeleteUserResponse.java
> +    }
여기도 동일하게 `@AllArgsConstructor` 대신 생성자를 직접 사용해준 이유가 있을까요??
이왕이면 일관성있게 가져가면 좋을 것 같습니다!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/dto/response/UpdateUserResponse.java
> +    public UpdateUserResponse(String phoneNumber, Department department, String imageUrl) {
한 줄 띄워주세요!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/dto/response/UpdateUserResponse.java
> +
ㅇ_ㅇ

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/service/UserService.java
> +        System.out.println(originPassword + "<>" + comparePassword);
해당 print문은 제거해도 될 것 같습니다!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/service/UserService.java
> +        DeleteUserResponse deleteUserResponse = new DeleteUserResponse(checkPassword(user.getPassword(), request.getPassword()));
120자를 넘어가네요!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/controller/UserController.java
> +    @GetMapping("/{userIdx}")
"userIdx" 인 이유가 있을까요??
userId에서 오타가 난 것 인지 userIndex인지 모르겠어요..ㅠ

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/controller/UserController.java
> +public class UserController {
controller에 대한 테스트가 없네요...ㅠ

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/domain/User.java
> +    }
이 두 메소드에 대한 테스트 코드도 있으면 좋을 것 같습니다!

2022-06-19 15:18 UTC, tco0427 commented on src/main/java/dankook/play/studentcouncilhomepage/service/UserService.java
> +public class UserService {
Service에 대한 테스트 코드가 누락된 것 같습니다..!

2022-06-19 15:26 UTC, developerChans commented on src/main/java/dankook/play/studentcouncilhomepage/controller/UserController.java
> +    @GetMapping("/{userIdx}")
userIndex입니다.하하

2022-06-20 08:16 UTC, headF1rst reviewed
커밋 메시지는 한국어로 통일하기로 하지 않았나요?
일관성을 위해서 통일하게 맞추는게 좋을것 같습니다.

2022-06-23 08:21 UTC, closed without merging